### ISSUE TITLE
Integrate Baserow (a.k.a. Pino)

### ISSUE THREAD

**Issue by xplosionmind** [scambifestival/scambi.org#13]
Test this in xplosionmind/tommi.space#7 first

**Comment by 2ale2** [comment]
Just so you know, as I said before, the Python script for synchronizing content on Pino (which can be cloned from my 'scambifestival-ubjs' repo) is currently working on a different branch (called 'scripts') of this repo in order to let people testing it. Once the script will be tested, I'll change the working branch.
